# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 454)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(200, 70, 411, 221))
        self.groupBox.setStyleSheet("background-color: rgb(239, 255, 238);")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label.setObjectName("label")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(10, 50, 371, 21))
        self.lineEditEmail.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPassword.setGeometry(QtCore.QRect(10, 110, 371, 21))
        self.lineEditPassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.checkBoxSave = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBoxSave.setGeometry(QtCore.QRect(10, 140, 191, 20))
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonLogin.setGeometry(QtCore.QRect(60, 170, 113, 32))
        self.pushButtonLogin.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("retail_project/uis/retail_project/imagine/ic_login_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonExit.setGeometry(QtCore.QRect(240, 170, 113, 32))
        self.pushButtonExit.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("retail_project/uis/retail_project/imagine/ic_exit_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon1)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 161, 181))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("retail_project/uis/retail_project/imagine/ic_login_screen.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonExit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Login System"))
        self.label.setText(_translate("MainWindow", "Email:"))
        self.lineEditEmail.setText(_translate("MainWindow", "putin@gmail.com"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.lineEditPassword.setText(_translate("MainWindow", "123"))
        self.checkBoxSave.setText(_translate("MainWindow", "Save login information"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Login"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
